In [1]:
import polars as pl 
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pl.read_csv('../data/raw/fraud_ecommerce/Fraud_Data.csv')

In [5]:
ip_df = pl.read_csv('../data/raw/fraud_ecommerce/IPAddress_to_Country.csv', ignore_errors=True)
ip_df

shape: (138_846, 3)
┌────────────────────────┬────────────────────────┬───────────┐
│ lower_bound_ip_address ┆ upper_bound_ip_address ┆ country   │
│ ---                    ┆ ---                    ┆ ---       │
│ i64                    ┆ i64                    ┆ str       │
╞════════════════════════╪════════════════════════╪═══════════╡
│ 16777216               ┆ 16777471               ┆ Australia │
│ 16777472               ┆ 16777727               ┆ China     │
│ 16777728               ┆ 16778239               ┆ China     │
│ 16778240               ┆ 16779263               ┆ Australia │
│ 16779264               ┆ 16781311               ┆ China     │
│ …                      ┆ …                      ┆ …         │
│ 3758092288             ┆ 3758093311             ┆ Hong Kong │
│ 3758093312             ┆ 3758094335             ┆ India     │
│ 3758095360             ┆ 3758095871             ┆ China     │
│ 3758095872             ┆ 3758096127             ┆ Singapore │
│ 3758096128             ┆ 3758096383             ┆ Australia │
└────────────────────────┴────────────────────────┴───────────┘

In [7]:
df

shape: (151_112, 11)
┌─────────┬─────────────┬───────────────┬────────────────┬───┬─────┬─────┬────────────┬───────┐
│ user_id ┆ signup_time ┆ purchase_time ┆ purchase_value ┆ … ┆ sex ┆ age ┆ ip_address ┆ class │
│ ---     ┆ ---         ┆ ---           ┆ ---            ┆   ┆ --- ┆ --- ┆ ---        ┆ ---   │
│ i64     ┆ str         ┆ str           ┆ i64            ┆   ┆ str ┆ i64 ┆ f64        ┆ i64   │
╞═════════╪═════════════╪═══════════════╪════════════════╪═══╪═════╪═════╪════════════╪═══════╡
│ 22058   ┆ 2015-02-24  ┆ 2015-04-18    ┆ 34             ┆ … ┆ M   ┆ 39  ┆ 7.3276e8   ┆ 0     │
│         ┆ 22:55:49    ┆ 02:47:11      ┆                ┆   ┆     ┆     ┆            ┆       │
│ 333320  ┆ 2015-06-07  ┆ 2015-06-08    ┆ 16             ┆ … ┆ F   ┆ 53  ┆ 3.5031e8   ┆ 0     │
│         ┆ 20:39:50    ┆ 01:38:54      ┆                ┆   ┆     ┆     ┆            ┆       │
│ 1359    ┆ 2015-01-01  ┆ 2015-01-01    ┆ 15             ┆ … ┆ M   ┆ 53  ┆ 2.6215e9   ┆ 1     │
│         ┆ 18:52:44    ┆ 18:52:45      ┆                ┆   ┆     ┆     ┆            ┆       │
│ 150084  ┆ 2015-04-28  ┆ 2015-05-04    ┆ 44             ┆ … ┆ M   ┆ 41  ┆ 3.8405e9   ┆ 0     │
│         ┆ 21:13:25    ┆ 13:54:50      ┆                ┆   ┆     ┆     ┆            ┆       │
│ 221365  ┆ 2015-07-21  ┆ 2015-09-09    ┆ 39             ┆ … ┆ M   ┆ 45  ┆ 4.1558e8   ┆ 0     │
│         ┆ 07:09:52    ┆ 18:40:53      ┆                ┆   ┆     ┆     ┆            ┆       │
│ …       ┆ …           ┆ …             ┆ …              ┆ … ┆ …   ┆ …   ┆ …          ┆ …     │
│ 345170  ┆ 2015-01-27  ┆ 2015-03-29    ┆ 43             ┆ … ┆ M   ┆ 28  ┆ 3.4512e9   ┆ 1     │
│         ┆ 03:03:34    ┆ 00:30:47      ┆                ┆   ┆     ┆     ┆            ┆       │
│ 274471  ┆ 2015-05-15  ┆ 2015-05-26    ┆ 35             ┆ … ┆ M   ┆ 32  ┆ 2.4390e9   ┆ 0     │
│         ┆ 17:43:29    ┆ 12:24:39      ┆                ┆   ┆     ┆     ┆            ┆       │
│ 368416  ┆ 2015-03-03  ┆ 2015-05-20    ┆ 40             ┆ … ┆ F   ┆ 26  ┆ 2.7485e9   ┆ 0     │
│         ┆ 23:07:31    ┆ 07:07:47      ┆                ┆   ┆     ┆     ┆            ┆       │
│ 207709  ┆ 2015-07-09  ┆ 2015-09-07    ┆ 46             ┆ … ┆ M   ┆ 37  ┆ 3.6012e9   ┆ 0     │
│         ┆ 20:06:07    ┆ 09:34:46      ┆                ┆   ┆     ┆     ┆            ┆       │
│ 138208  ┆ 2015-06-10  ┆ 2015-07-21    ┆ 20             ┆ … ┆ M   ┆ 38  ┆ 4.1038e9   ┆ 0     │
│         ┆ 07:02:20    ┆ 02:03:53      ┆                ┆   ┆     ┆     ┆            ┆       │
└─────────┴─────────────┴───────────────┴────────────────┴───┴─────┴─────┴────────────┴───────┘

In [8]:
df2 = pl.read_parquet('../data/processed/fraud_ecommerce.parquet')

In [11]:
df2

shape: (151_112, 11)
┌─────────────┬─────────────┬─────────────┬─────────────┬───┬─────┬─────────────┬────────┬─────────┐
│ signup_time ┆ time        ┆ purchase_va ┆ device_id   ┆ … ┆ age ┆ ip_address  ┆ target ┆ country │
│ ---         ┆ ---         ┆ lue         ┆ ---         ┆   ┆ --- ┆ ---         ┆ ---    ┆ ---     │
│ str         ┆ datetime[ns ┆ ---         ┆ str         ┆   ┆ i64 ┆ f64         ┆ i64    ┆ str     │
│             ┆ ]           ┆ i64         ┆             ┆   ┆     ┆             ┆        ┆         │
╞═════════════╪═════════════╪═════════════╪═════════════╪═══╪═════╪═════════════╪════════╪═════════╡
│ 2015-02-16  ┆ 2015-03-08  ┆ 46          ┆ ZCLZTAJPCRA ┆ … ┆ 36  ┆ 52093.49689 ┆ 0      ┆ Unknown │
│ 00:17:05    ┆ 10:00:39    ┆             ┆ QX          ┆   ┆     ┆ 5           ┆        ┆         │
│ 2015-03-08  ┆ 2015-03-20  ┆ 33          ┆ YFGYOALADBH ┆ … ┆ 30  ┆ 93447.13896 ┆ 0      ┆ Unknown │
│ 04:03:22    ┆ 17:23:45    ┆             ┆ LT          ┆   ┆     ┆ 1           ┆        ┆         │
│ 2015-05-17  ┆ 2015-05-26  ┆ 33          ┆ QZNVQTUITFT ┆ … ┆ 32  ┆ 105818.5015 ┆ 0      ┆ Unknown │
│ 16:45:54    ┆ 08:54:34    ┆             ┆ HH          ┆   ┆     ┆ 05          ┆        ┆         │
│ 2015-03-03  ┆ 2015-05-28  ┆ 33          ┆ PIBUQMBIELM ┆ … ┆ 40  ┆ 117566.6648 ┆ 0      ┆ Unknown │
│ 19:58:39    ┆ 21:09:13    ┆             ┆ MG          ┆   ┆     ┆ 67          ┆        ┆         │
│ 2015-03-20  ┆ 2015-04-05  ┆ 55          ┆ WFIIFCPIOGM ┆ … ┆ 38  ┆ 131423.7890 ┆ 0      ┆ Unknown │
│ 00:31:27    ┆ 07:31:46    ┆             ┆ HT          ┆   ┆     ┆ 42          ┆        ┆         │
│ …           ┆ …           ┆ …           ┆ …           ┆ … ┆ …   ┆ …           ┆ …      ┆ …       │
│ 2015-04-16  ┆ 2015-07-31  ┆ 39          ┆ DDZWCUYTHKA ┆ … ┆ 36  ┆ 4.2947e9    ┆ 0      ┆ Unknown │
│ 05:00:09    ┆ 21:21:47    ┆             ┆ LI          ┆   ┆     ┆             ┆        ┆         │
│ 2015-08-08  ┆ 2015-08-28  ┆ 62          ┆ YJLXUZPSHUO ┆ … ┆ 22  ┆ 4.2947e9    ┆ 0      ┆ Unknown │
│ 06:25:41    ┆ 04:01:06    ┆             ┆ OS          ┆   ┆     ┆             ┆        ┆         │
│ 2015-02-18  ┆ 2015-04-25  ┆ 17          ┆ LPIWPXJCMYJ ┆ … ┆ 19  ┆ 4.2947e9    ┆ 0      ┆ Unknown │
│ 21:07:18    ┆ 06:20:38    ┆             ┆ OT          ┆   ┆     ┆             ┆        ┆         │
│ 2015-08-15  ┆ 2015-10-30  ┆ 9           ┆ TSDCMHPWAUZ ┆ … ┆ 35  ┆ 4.2948e9    ┆ 0      ┆ Unknown │
│ 15:40:46    ┆ 09:47:39    ┆             ┆ AR          ┆   ┆     ┆             ┆        ┆         │
│ 2015-03-03  ┆ 2015-05-05  ┆ 39          ┆ JLVKRXCKCWN ┆ … ┆ 41  ┆ 4.2949e9    ┆ 0      ┆ Unknown │
│ 11:27:19    ┆ 10:32:46    ┆             ┆ LW          ┆   ┆     ┆             ┆        ┆         │
└─────────────┴─────────────┴─────────────┴─────────────┴───┴─────┴─────────────┴────────┴─────────┘