In [14]:
import polars as pl 
import matplotlib.pyplot as plt
import seaborn as sns

In [15]:
df = pl.read_csv('../data/raw/fraud_ecommerce/Fraud_Data.csv')

In [16]:
ip_df = pl.read_csv('../data/raw/fraud_ecommerce/IPAddress_to_Country.csv', ignore_errors=True)
ip_df

shape: (138_846, 3)
┌────────────────────────┬────────────────────────┬───────────┐
│ lower_bound_ip_address ┆ upper_bound_ip_address ┆ country   │
│ ---                    ┆ ---                    ┆ ---       │
│ i64                    ┆ i64                    ┆ str       │
╞════════════════════════╪════════════════════════╪═══════════╡
│ 16777216               ┆ 16777471               ┆ Australia │
│ 16777472               ┆ 16777727               ┆ China     │
│ 16777728               ┆ 16778239               ┆ China     │
│ 16778240               ┆ 16779263               ┆ Australia │
│ 16779264               ┆ 16781311               ┆ China     │
│ …                      ┆ …                      ┆ …         │
│ 3758092288             ┆ 3758093311             ┆ Hong Kong │
│ 3758093312             ┆ 3758094335             ┆ India     │
│ 3758095360             ┆ 3758095871             ┆ China     │
│ 3758095872             ┆ 3758096127             ┆ Singapore │
│ 3758096128             ┆ 3758096383             ┆ Australia │
└────────────────────────┴────────────────────────┴───────────┘

In [17]:
df

shape: (151_112, 11)
┌─────────┬─────────────┬───────────────┬────────────────┬───┬─────┬─────┬────────────┬───────┐
│ user_id ┆ signup_time ┆ purchase_time ┆ purchase_value ┆ … ┆ sex ┆ age ┆ ip_address ┆ class │
│ ---     ┆ ---         ┆ ---           ┆ ---            ┆   ┆ --- ┆ --- ┆ ---        ┆ ---   │
│ i64     ┆ str         ┆ str           ┆ i64            ┆   ┆ str ┆ i64 ┆ f64        ┆ i64   │
╞═════════╪═════════════╪═══════════════╪════════════════╪═══╪═════╪═════╪════════════╪═══════╡
│ 22058   ┆ 2015-02-24  ┆ 2015-04-18    ┆ 34             ┆ … ┆ M   ┆ 39  ┆ 7.3276e8   ┆ 0     │
│         ┆ 22:55:49    ┆ 02:47:11      ┆                ┆   ┆     ┆     ┆            ┆       │
│ 333320  ┆ 2015-06-07  ┆ 2015-06-08    ┆ 16             ┆ … ┆ F   ┆ 53  ┆ 3.5031e8   ┆ 0     │
│         ┆ 20:39:50    ┆ 01:38:54      ┆                ┆   ┆     ┆     ┆            ┆       │
│ 1359    ┆ 2015-01-01  ┆ 2015-01-01    ┆ 15             ┆ … ┆ M   ┆ 53  ┆ 2.6215e9   ┆ 1     │
│         ┆ 18:52:44    ┆ 18:52:45      ┆                ┆   ┆     ┆     ┆            ┆       │
│ 150084  ┆ 2015-04-28  ┆ 2015-05-04    ┆ 44             ┆ … ┆ M   ┆ 41  ┆ 3.8405e9   ┆ 0     │
│         ┆ 21:13:25    ┆ 13:54:50      ┆                ┆   ┆     ┆     ┆            ┆       │
│ 221365  ┆ 2015-07-21  ┆ 2015-09-09    ┆ 39             ┆ … ┆ M   ┆ 45  ┆ 4.1558e8   ┆ 0     │
│         ┆ 07:09:52    ┆ 18:40:53      ┆                ┆   ┆     ┆     ┆            ┆       │
│ …       ┆ …           ┆ …             ┆ …              ┆ … ┆ …   ┆ …   ┆ …          ┆ …     │
│ 345170  ┆ 2015-01-27  ┆ 2015-03-29    ┆ 43             ┆ … ┆ M   ┆ 28  ┆ 3.4512e9   ┆ 1     │
│         ┆ 03:03:34    ┆ 00:30:47      ┆                ┆   ┆     ┆     ┆            ┆       │
│ 274471  ┆ 2015-05-15  ┆ 2015-05-26    ┆ 35             ┆ … ┆ M   ┆ 32  ┆ 2.4390e9   ┆ 0     │
│         ┆ 17:43:29    ┆ 12:24:39      ┆                ┆   ┆     ┆     ┆            ┆       │
│ 368416  ┆ 2015-03-03  ┆ 2015-05-20    ┆ 40             ┆ … ┆ F   ┆ 26  ┆ 2.7485e9   ┆ 0     │
│         ┆ 23:07:31    ┆ 07:07:47      ┆                ┆   ┆     ┆     ┆            ┆       │
│ 207709  ┆ 2015-07-09  ┆ 2015-09-07    ┆ 46             ┆ … ┆ M   ┆ 37  ┆ 3.6012e9   ┆ 0     │
│         ┆ 20:06:07    ┆ 09:34:46      ┆                ┆   ┆     ┆     ┆            ┆       │
│ 138208  ┆ 2015-06-10  ┆ 2015-07-21    ┆ 20             ┆ … ┆ M   ┆ 38  ┆ 4.1038e9   ┆ 0     │
│         ┆ 07:02:20    ┆ 02:03:53      ┆                ┆   ┆     ┆     ┆            ┆       │
└─────────┴─────────────┴───────────────┴────────────────┴───┴─────┴─────┴────────────┴───────┘

In [18]:
df2 = pl.read_parquet('../data/processed/fraud_ecommerce.parquet')

In [19]:
df2

shape: (151_112, 16)
┌────────────┬────────────┬───────────┬─────┬───┬────────────┬────────────┬────────────┬───────────┐
│ time       ┆ purchase_v ┆ device_id ┆ sex ┆ … ┆ browser_Fi ┆ browser_IE ┆ browser_Op ┆ browser_S │
│ ---        ┆ alue       ┆ ---       ┆ --- ┆   ┆ reFox      ┆ ---        ┆ era        ┆ afari     │
│ datetime[n ┆ ---        ┆ f64       ┆ i64 ┆   ┆ ---        ┆ i8         ┆ ---        ┆ ---       │
│ s]         ┆ f64        ┆           ┆     ┆   ┆ i8         ┆            ┆ i8         ┆ i8        │
╞════════════╪════════════╪═══════════╪═════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ 2015-03-08 ┆ 3.850148   ┆ 0.093094  ┆ 1   ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 1         │
│ 10:00:39   ┆            ┆           ┆     ┆   ┆            ┆            ┆            ┆           │
│ 2015-03-20 ┆ 3.526361   ┆ 0.093597  ┆ 0   ┆ … ┆ 0          ┆ 1          ┆ 0          ┆ 0         │
│ 17:23:45   ┆            ┆           ┆     ┆   ┆            ┆            ┆            ┆           │
│ 2015-05-26 ┆ 3.526361   ┆ 0.094061  ┆ 0   ┆ … ┆ 1          ┆ 0          ┆ 0          ┆ 0         │
│ 08:54:34   ┆            ┆           ┆     ┆   ┆            ┆            ┆            ┆           │
│ 2015-05-28 ┆ 3.526361   ┆ 0.093739  ┆ 1   ┆ … ┆ 0          ┆ 1          ┆ 0          ┆ 0         │
│ 21:09:13   ┆            ┆           ┆     ┆   ┆            ┆            ┆            ┆           │
│ 2015-04-05 ┆ 4.025352   ┆ 0.093094  ┆ 1   ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 1         │
│ 07:31:46   ┆            ┆           ┆     ┆   ┆            ┆            ┆            ┆           │
│ …          ┆ …          ┆ …         ┆ …   ┆ … ┆ …          ┆ …          ┆ …          ┆ …         │
│ 2015-07-31 ┆ 3.688879   ┆ 0.093738  ┆ 0   ┆ … ┆ 1          ┆ 0          ┆ 0          ┆ 0         │
│ 21:21:47   ┆            ┆           ┆     ┆   ┆            ┆            ┆            ┆           │
│ 2015-08-28 ┆ 4.143135   ┆ 0.093094  ┆ 1   ┆ … ┆ 0          ┆ 1          ┆ 0          ┆ 0         │
│ 04:01:06   ┆            ┆           ┆     ┆   ┆            ┆            ┆            ┆           │
│ 2015-04-25 ┆ 2.890372   ┆ 0.093597  ┆ 1   ┆ … ┆ 1          ┆ 0          ┆ 0          ┆ 0         │
│ 06:20:38   ┆            ┆           ┆     ┆   ┆            ┆            ┆            ┆           │
│ 2015-10-30 ┆ 2.302585   ┆ 0.093094  ┆ 0   ┆ … ┆ 0          ┆ 1          ┆ 0          ┆ 0         │
│ 09:47:39   ┆            ┆           ┆     ┆   ┆            ┆            ┆            ┆           │
│ 2015-05-05 ┆ 3.688879   ┆ 0.093094  ┆ 0   ┆ … ┆ 1          ┆ 0          ┆ 0          ┆ 0         │
│ 10:32:46   ┆            ┆           ┆     ┆   ┆            ┆            ┆            ┆           │
└────────────┴────────────┴───────────┴─────┴───┴────────────┴────────────┴────────────┴───────────┘

In [20]:
df2.shape

(151112, 16)

In [21]:
df2.describe()

shape: (9, 17)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ time      ┆ purchase_ ┆ device_id ┆ … ┆ browser_F ┆ browser_I ┆ browser_O ┆ browser_ │
│ ---       ┆ ---       ┆ value     ┆ ---       ┆   ┆ ireFox    ┆ E         ┆ pera      ┆ Safari   │
│ str       ┆ str       ┆ ---       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ f64       ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 151112    ┆ 151112.0  ┆ 151112.0  ┆ … ┆ 151112.0  ┆ 151112.0  ┆ 151112.0  ┆ 151112.0 │
│ null_coun ┆ 0         ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 2015-06-1 ┆ 3.510192  ┆ 0.14264   ┆ … ┆ 0.162859  ┆ 0.243045  ┆ 0.024326  ┆ 0.163237 │
│           ┆ 6 02:56:3 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 8.759952  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ null      ┆ 0.520442  ┆ 0.200919  ┆ … ┆ 0.369239  ┆ 0.428923  ┆ 0.154061  ┆ 0.369583 │
│ min       ┆ 2015-01-0 ┆ 2.302585  ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 00:00:44  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ 2015-04-1 ┆ 3.135494  ┆ 0.093597  ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│           ┆ 8         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 14:41:31  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 50%       ┆ 2015-06-1 ┆ 3.583519  ┆ 0.093738  ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│           ┆ 8         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 13:46:47  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 75%       ┆ 2015-08-1 ┆ 3.912023  ┆ 0.093739  ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│           ┆ 7         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 18:48:31  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ max       ┆ 2015-12-1 ┆ 5.043425  ┆ 1.0       ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 02:56:05  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘